parameters:
    version: 2
    db_type: mysql_dsn
    mysql_dsn: 'mysql://root:root@localhost:3306'
    perm_type: linuxAcl
    perm_user: www-data
    hosts_type: file
    httpd_type: apache24
    httpd_restart_command: 'service apache2 restart'
services: {  }
